[package]
name = "verb_beta"
version = "0.1.0"
edition = "2024"

[dependencies]
# core async runtime
axum = { version = "0.8.8", features = ["macros"] }
# web framework- axum with macros for routing
tokio = { version = "1.49.0", features = ["full"] }
